# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CMU Data Interaction Group
description: >- # this means to ignore newlines until "baseurl:"
  We are a research group at the Human-Computer Interaction Institute at 
  Carnegie Mellon University. Our mission is to empower everyone to analyze and 
  communicate data with interactive systems.
email: dig@cmu.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dig.cmu.edu" # the base hostname & protocol for your site, e.g. http://example.com
page_url: "https://github.com/cmudig/cmudig.github.io/edit/main/"
twitter_username: cmudig
github_username: cmudig

sass:
  style: compressed
  load_paths:
    - node_modules

collections:
  publications:
    output: true
  people:
    output: true
  courses:
    output: true

languages: ["zh", "en"]
default_lang: "zh"
exclude_from_localization: ["assets"]
parallel_localization: true
lang_from_path: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-polyglot
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-redirect-from
kramdown:
  toc_levels: 1..2
