name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          build_only: true
